language: node_js

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install -y tcl-dev; fi

node_js:
  - "0.10"
  - "node"
  - "iojs"

script:
  - npm run lint
  - npm test

after_success:
  - npm run coveralls

